name: Test
on:
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Docker build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build image
      run: make docker
  test_go_get:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.14', '1.13', '1.12' ]
    name: Go get with Go ${{ matrix.go }}
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go }}
    - name: Go get Signalilo
      run: go get github.com/vshn/signalilo
